[workspace]
members = [
    "toshi-server",
    "toshi-proto",
    "toshi-client",
    "toshi-types",
    "toshi-test",
    "toshi-raft"
]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = true
rpath = false
codegen-units = 1